language: cpp

stages:
  - build
  - test

addons:
  apt:
    update: true
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - libboost-all-dev

  homebrew:
    update: true
    packages:
      - qt5
      - boost

jobs:
  include:

    ###############################
    ##            TEST
    ###############################

    - stage: test
      os: linux
      dist: focal
      language: cpp
      compiler: gcc
      install: &install_linux
        - wget https://github.com/Kitware/CMake/releases/download/v3.15.7/cmake-3.15.7-Linux-x86_64.tar.gz
        - tar -xf cmake-3.15.7-Linux-x86_64.tar.gz
        - export PATH=`pwd`/cmake-3.15.7-Linux-x86_64/bin:$PATH
      before_script: &before_script
        - cd build
      script: &script_linux_test
        - cmake ..
        - make getit_tests
        - ./bin/getit_tests
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: test
      os: linux
      dist: focal
      language: cpp
      compiler: clang
      install: *install_linux
      before_script: *before_script
      script: *script_linux_test

    - stage: test
      os: osx
      osx_image: xcode12.2
      language: cpp
      compiler: gcc
      install: &install_macos
        - wget https://github.com/Kitware/CMake/releases/download/v3.15.7/cmake-3.15.7-Darwin-x86_64.tar.gz
        - tar -xf cmake-3.15.7-Darwin-x86_64.tar.gz
        - export PATH=`pwd`/cmake-3.15.7-Darwin-x86_64/bin:$PATH
      before_script: *before_script
      script: &script_macos_test
        - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
        - make getit_tests
        - ./bin/getit_tests

    - stage: test
      os: osx
      osx_image: xcode12.2
      compiler: clang
      install: *install_macos
      before_script: *before_script
      script: *script_macos_test

    ###############################
    ##            BUILD
    ###############################
    - stage: build
      os: linux
      dist: focal
      language: cpp
      compiler: gcc
      install: *install_linux
      before_script: *before_script
      script: &script_linux_build
        - cmake ..
        - make getit

    - stage: build
      os: linux
      dist: focal
      language: cpp
      compiler: clang
      install: *install_linux
      before_script: *before_script
      script: *script_linux_build

    - stage: build
      os: osx
      osx_image: xcode12.2
      language: cpp
      compiler: gcc
      install: *install_macos
      before_script: *before_script
      script: &script_macos_build
        - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
        - make getit

    - stage: build
      os: osx
      osx_image: xcode12.2
      language: cpp
      compiler: clang
      install: *install_macos
      before_script: *before_script
      script: *script_macos_build
