name: Build & Test GetIt

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: sudo apt update && sudo apt install -yq libboost-all-dev
    - name: Install Qt5
      run: sudo apt update && sudo apt install -yq build-essential libgl1-mesa-dev qt5-default
    - name: Install CMake
      run: sudo apt update && sudo apt install -yq cmake
    - name: Run CMake
      run: cmake .
    - name: Build GetIt
      run: make getit
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: sudo apt update && sudo apt install -yq libboost-all-dev
    - name: Install Qt5
      run: sudo apt update && sudo apt install -yq build-essential libgl1-mesa-dev qt5-default
    - name: Install CMake
      run: sudo apt update && sudo apt install -yq cmake
    - name: Run CMake
      run: cmake . -D CMAKE_CXX_FLAGS="fprofile-instr-generate -fcoverage-mapping" 
    - name: Build GetIt tests
      run: make getit_tests
    - name: Run tests
      run: ./bin/getit_tests
    - uses: codecov/codecov-action@v2.1.0
    
