name: Build & Test GetIt on all platforms
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            generator: Ninja
            openssl_root: /usr
            test_command: ./bin/getit_tests

          - os: macos-latest
            generator: Ninja
            openssl_root: /usr/local/opt/openssl@3
            test_command: ./bin/getit_tests

          - os: windows-latest
            generator: Ninja
            openssl_root: D:\msys2\msys64\mingw64
            test_command: & bin/getit_tests.exe

    runs-on: ${{matrix.os}}
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_mingw81

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          location: ${{env.msys}}
          msystem: mingw64
          install: mingw-w64-x86_64-openssl mingw-w64-x86_64-boost mingw-w64-x86_64-ninja

      - name: Install MacOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install openssl boost ninja

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libboost-all-dev libssl-dev cmake ninja

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create GetIt project
        run: cmake . -G "${{matrix.generator}}" -Dpackaging=true -DCMAKE_CXX_FLAGS='-w' -DOPENSSL_ROOT_DIR=${{matrix.openssl_root}}

      - name: Build GetIt
        run: ninja GetIt

      - name: Build GetIt tests
        run: ninja getit_tests

      - name: Execute GetIt tests
        run: ${{matrix.test_command}}