name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: sudo apt update && sudo apt install -yq libboost1.65-dev
    - name: Install Qt6
      run: sudo apt update && sudo apt install -yq build-essential libgl1-mesa-dev
    - name: Install CMake
      run: sudo apt update && sudo apt install -yq cmake
    - name: Create and open build directory
      run: mkdir build && cd ./build
    - name: Run CMake
      run: cmake ..
    - name: Build GetIt
      run: make getit
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install boost
      run: sudo apt update && sudo apt install -yq libboost1.65-dev
    - name: Install Qt6
      run: sudo apt update && sudo apt install -yq build-essential libgl1-mesa-dev
    - name: Install CMake
      run: sudo apt update && sudo apt install -yq cmake
    - name: Create and open build directory
      run: mkdir build && cd ./build
    - name: Run CMake
      run: cmake ..
    - name: Build GetIt tests
      run: make getit_tests
    - name: Run tests
      run: ./bin/getit_tests
    
