name: Build Linux Flatpak

on:
  create:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build Linux Flatpak
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt update && sudo apt upgrade -y
      - name: Install dependencies
        run: sudo apt install -y libboost-all-dev qt6-base-dev ninja-build cmake flatpak-builder flatpak
      - name: Create GetIt flatpak
        run: bash ./packaging/linux/package.sh
      - name: Upload GetIt flatpak as build artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: GetIt-Linux-Flatpak.zip
          path: ./getit.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./getit.zip
          asset_name: GetIt-Linux-x64.zip
          tag: ${{ github.ref }}


