name: Build Linux Flatpak

on:
  create:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build Linux Flatpak
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt update && sudo apt upgrade -y
      - name: Install dependencies
        run: sudo apt install -y libboost-all-dev qt5-default ninja-build cmake flatpak-builder flatpak
      - name: Prepare flatpak template
        run:  cmake .  -G Ninja -Dpackaging=true
      - name: Add Flathub to flatpak refs
        run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - name: Run flatpak repair
        run: flatpak repair --user --reinstall-all
      - name: Install Qt/Kde runtime
        run: flatpak install --user flathub org.kde.Platform/5.15-21.08
      - name: Install Qt/Kde SDK
        run: flatpak install --user flathub org.kde.Sdk/5.15-21.08       
      - name: Create flatpak repository for GetIt
        run: flatpak-builder --repo=getit_repo getit ./packaging/linux/getit.yml
      - name: Create flatpak bundle
        run: flatpak build-bundle getit_repo getit.flatpak net.bartkessels.getit
      - name: Zip flatpak bundle
        run: zip -rT getit.zip ./bin/getit.flatpak >> /dev/null
      - name: Upload GetIt flatpak as build artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: GetIt-Linux-Flatpak.zip
          path: ./getit.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./getit.zip
          asset_name: GetIt-Linux-x64.zip
          tag: ${{ github.ref }}
