name: Build MacOS package

on:
  create:
    tags:
      - v*

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build MacOS package
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install boost qt ninja cmake
    - name: Create GetIt bundle
      run: zsh ./packaging/macos/package.sh
    - name: Upload MacOS bundle artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: ./bin/GetIt.app
    
      
