name: Build MacOS package

on:
  create:
    tags:
      - v*

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build MacOS package
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install boost qt ninja cmake
    - name: Create GetIt bundle
      run: zsh ./packaging/macos/package.sh
    - name: Upload MacOS bundle as build artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: GetIt.app
        path: ./bin/GetIt.app
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload MacOS bundle as release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/GetIt.app
        asset_name: GetIt-MacOS-x64.app
        asset_content_type: application
    
      
