name: Build MacOS package

on:
  create:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build MacOS package
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install boost qt ninja cmake
    - name: Create GetIt project
      run: cmake . -G Ninja -Dpackaging=true -DUseQt6=true -DCMAKE_CXX_FLAGS="-w"
    - name: Create GetIt Bundle
      run: ninja GetIt
    - name: Link Qt to app bundle
      run: macdeployqt ./bin/GetIt.app -timestamp -libpath=./_deps
    - name: Copy icon to MacOS Bundle
      run: cp ./packaging/macos/icons/getit.icns ./bin/GetIt.app/Contents/Resources
    - name: Zip MacOS Bundle
      run: zip -rT getit.zip ./bin/GetIt.app >> /dev/null
    - name: Upload MacOS bundle as build artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: GetIt-MacOS-x64.zip
        path: ./getit.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./getit.zip
        asset_name: GetIt-MacOS-x64.zip
        tag: ${{ github.ref }}
    
      
