name: Build Windows executable

on:
  create:
    tags:
      - v*

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build Windows executable
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add VCPKG installation path to PATH variable
      run: set PATH=%PATH%;C:\vcpkg
    - name: Install dependencies (Choco)
      run: choco install -y qtcreator qt5-default ninja cmake
    - name: Install dependencies (VCPKG)
      run: vcpkg install boost
    - name: Create GetIt executable
      run: packaging/windows/package.cmd
    - name: Upload Windows executable as build artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: GetIt-Windows-x64.zip
        path: ./getit.zip
