name: Build Windows executable

on:
  create:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build Windows executable
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add VCPKG installation path to PATH variable
      run: $Env:PATH += ";C:\vcpkg"
    - name: Install dependencies (Choco)
      run: choco install -y qtcreator qt5-default ninja cmake
    - name: Install dependencies (VCPKG)
      run: vcpkg install boost-date-time:x64-windows-static boost-regex:x64-windows-static boost-system:x64-windows-static boost-interprocess:x64-windows-static
    - name: Create GetIt executable
      run: ./packaging/windows/package.ps1
    - name: Upload Windows executable as build artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: GetIt-Windows-x64.zip
        path: ./getit.zip
